title: Product
required:
  - id
  - name
  - amount
  - price
type: object
properties:
  id:
    type: string
    example: 0
  name:
    type: string
    example: ProductA
  amount:
    type: integer
    format: int32
    example: 1
  price:
    type: integer
    format: int32
    example: 599
